export const userConstants = {
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    DRIVER_LOGIN_SUCCESS: 'DRIVER_LOGIN_SUCCESS',
    DRIVER_LOGIN_FAILURE: 'DRIVER_LOGIN_FAILURE',

    OTP_VERIFICATION_SUCCESS: 'OTP_VERIFICATION_SUCCESS',
    OTP_VERIFICATION_FAILURE: 'OTP_VERIFICATION_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',
};