export const userConstants = {
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    DRIVER_LOGIN_SUCCESS: 'DRIVER_LOGIN_SUCCESS',
    DRIVER_LOGIN_FAILURE: 'DRIVER_LOGIN_FAILURE',

    OTP_VERIFICATION_SUCCESS: 'OTP_VERIFICATION_SUCCESS',
    OTP_VERIFICATION_FAILURE: 'OTP_VERIFICATION_FAILURE',

    DRIVER_OTP_VERIFICATION_SUCCESS: 'DRIVER_OTP_VERIFICATION_SUCCESS',
    DRIVER_OTP_VERIFICATION_FAILURE: 'DRIVER_OTP_VERIFICATION_FAILURE',

    DRIVER_REGISTRATION_CHECK_SUCCESS: 'DRIVER_REGISTRATION_CHECK_SUCCESS',
    DRIVER_REGISTRATION_CHECK_FAILURE: 'DRIVER_REGISTRATION_CHECK_FAILURE',

    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    ACCEPT_TASK_SUCCESS: 'ACCEPT_TASK_SUCCESS',
    ACCEPT_TASK_FAILURE: 'ACCEPT_TASK_FAILURE',

    PICKUP_TASK_SUCCESS: 'PICKUP_TASK_SUCCESS',
    PICKUP_TASK_FAILURE: 'PICKUP_TASK_FAILURE',

    DELIVERED_TASK_SUCCESS: 'DELIVERED_TASK_SUCCESS',
    DELIVERED_TASK_FAILURE: 'DELIVERED_TASK_FAILURE',

    CANCEL_TASK_SUCCESS: 'CANCEL_TASK_SUCCESS',
    CANCEL_TASK_FAILURE: 'CANCEL_TASK_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',
};